FORMAT: 1A
HOST: http://10.14.41.20:8081/api

# Tada API

API spec for Tada project. 

## Labels [/labels]

### Get several labels [POST] 

Get labels

+ Schema
    {
        "view_count_range": ["0", "Infinity"],
        "like_ratio_range": ["0", "1"]
    }

+ Request (application/json)

    + Attributes
        + view_count_range (required, array) - View count range [0, 9999]
        + like_ratio_range (required, array) - Like ratio [0, 100]

+ Response 200 (application/json)
        
        {
            "total": 2,
            "labels": {
                "59e1570ec7e0c22a00d7648e": "Darth Vader",
                "59e92e81dc4aaf47c4e09871": "Luke"
            }
        }

<!--
## Label [/labels/{id}]

### Get one label [GET]

Get a label's data, related labels(sorted by confidence), and videos(grouped by hour) under this label.

+ Response 200 (application/json)

        {
            "name": "Darth Vador",
            "id": "asdfasdfasdf",
            "video_count": 123343,
            "relations": [{
                "id": "asdfasdfasdf",
                "name": "Battlefront2",
                "is_meta": true,
                "count": 455
            },{
                "id": "asdfasdfasdf",
                "name": "Starwhat",
                "is_meta": false,
                "count": 450
            }],
            "history": {
                "grouped_by": "hour",
                "videos": [[{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                }], [{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                }]]
            }


## Filter Labels [/filter-labels]
### Get labels under current viewcount range and like ratio range [POST]
+ Request (application/json)

    + Attributes
        + view_count_range (required, array) - View count range [0, 9999]
        + like_ratio_range (required, array) - Like ratio [0, 100]

-->

## Filter Videos [/filter-videos]

### Get videos under multiple labels (intersection), with current viewcount range and like ratio range [POST]

Get video ids containing the intersection of these labels under the constraints of view count and like ratio.

+ Schema
    {
        "ids": ["59e1570ec7e0c22a00d7648e", "59e92e81dc4aaf47c4e09871"],
        "view_count_range": ["0", "Infinity"],
        "like_ratio_range": ["0", "1"]
    }

+ Request (application/json)

    + Attributes
        + ids (required, array) - Array of ids [1, 2, 3..]
        + view_count_range (required, array) - View count range [0, 9999]
        + like_ratio_range (required, array) - Like ratio [0, 100]
    
+ Response 200 (application/json)

        {  
           "total":20,
           "positions":{  
              "59e1570ec7e0c22a00d7649f":{  
                 "3600":[  
                    [141,0],
                    [141,0],
                    [141,0],
                    [141,0]
                 ],
                 "21600":[  
                    [23,0],
                    [23,0],
                    [23,0],
                    [23,0]
                 ],
                 "43200":[  
                    [11,0],
                    [11,0],
                    [11,0],
                    [11,0]
                 ]
              },
              "59e626b531b15d2b9cf68ac4":{  
                 "3600":[  
                    [228,0],
                    [228,0],
                    [228,0],
                    [228,0]
                 ],
                 "21600":[  
                    [38,1],
                    [38,1],
                    [38,1],
                    [38,1]
                 ],
                 "43200":[  
                    [19,2],
                    [19,1],
                    [19,2],
                    [19,1]
                 ]
              },
              "59e6407b31b15d2b9cf68b94":{  
                 "3600":[  
                    [230,0],
                    [230,1],
                    [230,0],
                    [230,1]
                 ],
                 "21600":[  
                    [38,0],
                    [38,2],
                    [38,0],
                    [38,2]
                 ],
                 "43200":[  
                    [19,0],
                    [19,3],
                    [19,0],
                    [19,3]
                 ]
              },
              "59e6407b31b15d2b9cf68b9c":{  
                 "3600":[  
                    [230,1],
                    [230,0],
                    [230,],
                    [230,0]
                 ],
                 "21600":[  
                    [38,2],
                    [38,0],
                    [38,2],
                    [38,0]
                 ],
                 "43200":[  
                    [19,3],
                    [19,0],
                    [19,3],
                    [19,0]
                 ]
              },
              "59e6a5414673693a8c4b6583":{  
                 "3600":[  
                    [237,0],
                    [237,0],
                    [237,0],
                    [237,0]
                 ],
                 "21600":[  
                    [39,0],
                    [39,0],
                    [39,0],
                    [39,0]
                 ],
                 "43200":[  
                    [19,1],
                    [19,2],
                    [19,1],
                    [19,2]
                 ]
              },
              "59ea016aa55ffb26b0945686":{  
                 "3600":[  
                    [299,0],
                    [299,0],
                    [299,0],
                    [299,0]
                 ],
                 "21600":[  
                    [49,0],
                    [49,0],
                    [49,0],
                    [49,0]
                 ],
                 "43200":[  
                    [24,0],
                    [24,0],
                    [24,0],
                    [24,0]
                 ]
              },
              "59ea2493a55ffb26b09456f3":{  
                 "3600":[  
                    [301,0],
                    [301,0],
                    [301,0],
                    [301,0]
                 ],
                 "21600":[  
                    [50,0],
                    [50,0],
                    [50,0],
                    [50,0]
                 ],
                 "43200":[  
                    [25,0],
                    [25,0],
                    [25,0],
                    [25,0]
                 ]
              },
              "59ee120ca55ffb26b094632f":{  
                 "3600":[  
                    [373,1],
                    [373,0],
                    [373,1],
                    [373,0]
                 ],
                 "21600":[  
                    [62,1],
                    [62,0],
                    [62,1],
                    [62,0]
                 ],
                 "43200":[  
                    [31,1],
                    [31,0],
                    [31,1],
                    [31,0]
                 ]
              },
              "59ee1911a55ffb26b094635d":{  
                 "3600":[  
                    [373,0],
                    [373,1],
                    [373,0],
                    [373,1]
                 ],
                 "21600":[  
                    [62,0],
                    [62,1],
                    [62,0],
                    [62,1]
                 ],
                 "43200":[  
                    [31,0],
                    [31,1],
                    [31,0],
                    [31,1]
                 ]
              },
              "59ef324f5e63dd461087af99":{  
                 "3600":[  
                    [393,0],
                    [393,0],
                    [393,0],
                    [393,0]
                 ],
                 "21600":[  
                    [65,1],
                    [65,0],
                    [65,1],
                    [65,0]
                 ],
                 "43200":[  
                    [32,1],
                    [32,0],
                    [32,1],
                    [32,0]
                 ]
              },
              "59ef395b5e63dd461087afba":{  
                 "3600":[  
                    [394,0],
                    [394,0],
                    [394,0],
                    [394,0]
                 ],
                 "21600":[  
                    [65,0],
                    [65,1],
                    [65,0],
                    [65,1]
                 ],
                 "43200":[  
                    [32,0],
                    [32,1],
                    [32,0],
                    [32,1]
                 ]
              },
              "59f0ed495e63dd461087b4e0":{  
                 "3600":[  
                    [425,0],
                    [425,0],
                    [425,0],
                    [425,0]
                 ],
                 "21600":[  
                    [70,0],
                    [70,0],
                    [70,0],
                    [70,0]
                 ],
                 "43200":[  
                    [35,0],
                    [35,0],
                    [35,0],
                    [35,0]
                 ]
              },
              "59f0ed495e63dd461087b4e1":{  
                 "3600":[  
                    [425,1],
                    [425,1],
                    [425,1],
                    [425,1]
                 ],
                 "21600":[  
                    [70,1],
                    [70,1],
                    [70,1],
                    [70,1]
                 ],
                 "43200":[  
                    [35,2],
                    [35,1],
                    [35,2],
                    [35,1]
                 ]
              },
              "59f110745e63dd461087b558":{  
                 "3600":[  
                    [427,0],
                    [427,0],
                    [427,0],
                    [427,0]
                 ],
                 "21600":[  
                    [71,0],
                    [71,0],
                    [71,0],
                    [71,0]
                 ],
                 "43200":[  
                    [35,1],
                    [35,2],
                    [35,1],
                    [35,2]
                 ]
              },
              "59f1c7445e63dd461087b781":{  
                 "3600":[  
                    [440,0],
                    [440,0],
                    [440,0],
                    [440,0]
                 ],
                 "21600":[  
                    [73,0],
                    [73,0],
                    [73,0],
                    [73,0]
                 ],
                 "43200":[  
                    [36,0],
                    [36,0],
                    [36,0],
                    [36,0]
                 ]
              },
              "59f27005984a1f0d1c5a64e1":{  
                 "3600":[  
                    [452,0],
                    [452,0],
                    [452,0],
                    [452,0]
                 ],
                 "21600":[  
                    [75,0],
                    [75,0],
                    [75,0],
                    [75,0]
                 ],
                 "43200":[  
                    [37,0],
                    [37,0],
                    [37,0],
                    [37,0]
                 ]
              },
              "59fd03006114c46bb476d3bd":{  
                 "3600":[  
                    [644,0],
                    [644,0],
                    [644,0],
                    [644,0]
                 ],
                 "21600":[  
                    [107,0],
                    [107,0],
                    [107,0],
                    [107,0]
                 ],
                 "43200":[  
                    [53,0],
                    [53,0],
                    [53,0],
                    [53,0]
                 ]
              },
              "59fd03016114c46bb476d3c5":{  
                 "3600":[  
                    [584,0],
                    [584,0],
                    [584,0],
                    [584,0]
                 ],
                 "21600":[  
                    [97,0],
                    [97,0],
                    [97,0],
                    [97,0]
                 ],
                 "43200":[  
                    [48,0],
                    [48,0],
                    [48,0],
                    [48,0]
                 ]
              },
              "59fd7a886114c46bb476d45e":{  
                 "3600":[  
                    [651,0],
                    [651,0],
                    [651,0],
                    [651,0]
                 ],
                 "21600":[  
                    [108,0],
                    [108,0],
                    [108,0],
                    [108,0]
                 ],
                 "43200":[  
                    [54,0],
                    [54,0],
                    [54,0],
                    [54,0]
                 ]
              },
              "59fe70a26114c46bb476d668":{  
                 "3600":[  
                    [670,0],
                    [670,0],
                    [670,0],
                    [670,0]
                 ],
                 "21600":[  
                    [111,0],
                    [111,0],
                    [111,0],
                    [111,0]
                 ],
                 "43200":[  
                    [55,0],
                    [55,0],
                    [55,0],
                    [55,0]
                 ]
              }
           }
        }


## Video [/videos/{id}]

+ Parameters
    + id - a unique database ID for the video
    
### Get one video [GET]

Get a video's data and its labels(sorted by confidence).

+ Response 200 (application/json)

        {
            "id": "59fa7a66f1d4222ad4d38be2",
            "href": "https://www.youtube.com/watch?v=tm32FFFbAOk",
            "channel": "YouTube",
            "stats": {
                "view_count": 150212,
                "like_count": 4087,
                "dislike_count": 452,
                "fav_count": 0,
                "comment_count": 1410,
                "vl_ratio": 0.027208212393151014,
                "last_mention": {
                    "timestamp": 1509593439,
                    "source": "twitter",
                    "source_id": "925928112797437952"
                }
            },
            "title": "Lucasfilm President Kathleen Kennedy on All Things Star Wars, Kylo Ren in Battlefront II, and More!",
            "timestamp": 1509565767,
            "labels": [
                {
                    "_id": "59fa7a66f1d4222ad4d38bd8",
                    "name": "kathleen kennedi",
                    "is_meta": false,
                    "score": 0.619994044303894,
                    "count": 0
                },
                {
                    "_id": "59fa7a66f1d4222ad4d38bd9",
                    "name": "lucasfilm",
                    "is_meta": false,
                    "score": 0.20345813035964966,
                    "count": 0
                },
                {
                    "_id": "59fa7a66f1d4222ad4d38bda",
                    "name": "all things star war",
                    "is_meta": false,
                    "score": 0.05823218822479248,
                    "count": 0
                },
                {
                    "_id": "59e568da31b15d2b9cf68722",
                    "name": "kylo ren",
                    "is_meta": false,
                    "score": 0.053460799157619476,
                    "count": 0
                },
                {
                    "_id": "59e15967cd25d81dc417c29d",
                    "name": "more",
                    "is_meta": false,
                    "score": 0.046916767954826355,
                    "count": 0
                },
                {
                    "_id": "59e92e77dc4aaf47c4e09870",
                    "name": "swbf2",
                    "is_meta": true,
                    "score": 0.017938053235411644,
                    "count": 0
                }
            ]
        }

## Search [/search/{?q}]

+ Parameters
    + q (string) - query input from user
    
### Search for a label [POST]
WIP
    
+ Response 200 (application/json)

        {
            "name": "Darth Vador",
            "id": "asdfasdfasdf",
            "video_count": 123343,
            "relations": [{
                "id": "asdfasdfasdf",
                "name": "Battlefront2",
                "count": 455
            },{
                "id": "asdfasdfasdf",
                "name": "Starwhat",
                "count": 450
            }],
            "history": {
                "grouped_by": "hour",
                "videos": [[{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123
                }], [{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123
                }]]
            }
        }