FORMAT: 1A
HOST: http://10.14.41.20:8081/api

# Tada API

API spec for Tada project. 
<!--
## Labels [/labels]

### Get several labels [GET] 
WIP
+ Response 200 (application/json)

        {
            "description": {
                "sorted_by": "popularity",
                "label_count": 18283848
            },
            "data": [[
                "name": "Darth vador",
                "id": "asdfasdfasdfasdf",
                "is_meta": true,
                "video_count": 123412
            ],[
                "name": "Dar",
                "id": "asdfasdfasdfasdf",
                "is_meta": false,
                "video_count": 123412
            ],[
                "name": "dor",
                "id": "asdfasdfasdfasdf",
                "is_meta": false,
                "video_count": 123412
            ]]
        }


## Label [/labels/{id}]

### Get one label [GET]

Get a label's data, related labels(sorted by confidence), and videos(grouped by hour) under this label.

+ Response 200 (application/json)

        {
            "name": "Darth Vador",
            "id": "asdfasdfasdf",
            "video_count": 123343,
            "relations": [{
                "id": "asdfasdfasdf",
                "name": "Battlefront2",
                "is_meta": true,
                "count": 455
            },{
                "id": "asdfasdfasdf",
                "name": "Starwhat",
                "is_meta": false,
                "count": 450
            }],
            "history": {
                "grouped_by": "hour",
                "videos": [[{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                }], [{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123,
                    "labels": ["label1", "label2", "label3", "label4"]
                }]]
            }
-->
## Filter [/filter]

### Get videos under multiple labels (intersection), with current viewcount range and like ratio range [POST]

Get video ids containing the intersection of these labels under the constraints of view count and like ratio.
+ Request (application/json)

    + Attributes
        + ids (required, array) - Array of ids [1, 2, 3..]
        + view_count_range (required, array) - View count range [0, 9999]
        + like_ratio_range (required, array) - Like ratio [0, 100]
    
+ Response 200 (application/json)

        {
            "total": 3,
            "circle-positions": {
                "59e92e77dc4aaf47c4e09870": {
                    "3600": [
                        [0, 1], 
                        [0, 1],
                        [0, 1],
                        [3, 0]
                    ],
                    "21600": [
                        [1, 5],
                        [6, 8],
                        [0, 1],
                        [80, 1]
                    ],
                    "43200": [
                        [0, 1],
                        [3, 9],
                        [34, 5],
                        [6, 32]
                    ]
                },
                "59e92e73dc4aaf47c4e09865": {
                    "3600": [
                        [0, 1], 
                        [0, 1],
                        [0, 1],
                        [3, 0]
                    ],
                    "21600": [
                        [1, 5],
                        [6, 8],
                        [0, 1],
                        [80, 1]
                    ],
                    "43200": [
                        [0, 1],
                        [3, 9],
                        [34, 5],
                        [6, 32]
                    ]
                },
                "59e92e77dc4aaf37c4e09870": {
                    "3600": [
                        [0, 1], 
                        [0, 1],
                        [0, 1],
                        [3, 0]
                    ],
                    "21600": [
                        [1, 5],
                        [6, 8],
                        [0, 1],
                        [80, 1]
                    ],
                    "twelve-hour": [
                        [0, 1],
                        [3, 9],
                        [34, 5],
                        [6, 32]
                    ]
                }
            }
        }


## Video [/videos/{id}]

+ Parameters
    + id - a unique database ID for the video
    
### Get one video [GET]

Get a video's data and its labels(sorted by confidence).

+ Response 200 (application/json)

        {
            "id": "59fa7a66f1d4222ad4d38be2",
            "href": "https://www.youtube.com/watch?v=tm32FFFbAOk",
            "channel": "YouTube",
            "stats": {
                "view_count": 150212,
                "like_count": 4087,
                "dislike_count": 452,
                "fav_count": 0,
                "comment_count": 1410,
                "vl_ratio": 0.027208212393151014,
                "last_mention": {
                    "timestamp": 1509593439,
                    "source": "twitter",
                    "source_id": "925928112797437952"
                }
            },
            "title": "Lucasfilm President Kathleen Kennedy on All Things Star Wars, Kylo Ren in Battlefront II, and More!",
            "timestamp": 1509565767,
            "labels": [
                {
                    "_id": "59fa7a66f1d4222ad4d38bd8",
                    "name": "kathleen kennedi",
                    "is_meta": false,
                    "score": 0.619994044303894,
                    "count": 0
                },
                {
                    "_id": "59fa7a66f1d4222ad4d38bd9",
                    "name": "lucasfilm",
                    "is_meta": false,
                    "score": 0.20345813035964966,
                    "count": 0
                },
                {
                    "_id": "59fa7a66f1d4222ad4d38bda",
                    "name": "all things star war",
                    "is_meta": false,
                    "score": 0.05823218822479248,
                    "count": 0
                },
                {
                    "_id": "59e568da31b15d2b9cf68722",
                    "name": "kylo ren",
                    "is_meta": false,
                    "score": 0.053460799157619476,
                    "count": 0
                },
                {
                    "_id": "59e15967cd25d81dc417c29d",
                    "name": "more",
                    "is_meta": false,
                    "score": 0.046916767954826355,
                    "count": 0
                },
                {
                    "_id": "59e92e77dc4aaf47c4e09870",
                    "name": "swbf2",
                    "is_meta": true,
                    "score": 0.017938053235411644,
                    "count": 0
                }
            ]
        }

## Search [/search/{?q}]

+ Parameters
    + q (string) - query input from user
    
### Search for a label [POST]
WIP
    
+ Response 200 (application/json)

        {
            "name": "Darth Vador",
            "id": "asdfasdfasdf",
            "video_count": 123343,
            "relations": [{
                "id": "asdfasdfasdf",
                "name": "Battlefront2",
                "count": 455
            },{
                "id": "asdfasdfasdf",
                "name": "Starwhat",
                "count": 450
            }],
            "history": {
                "grouped_by": "hour",
                "videos": [[{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123
                }], [{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.1",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.2",
                    "title": "One Awesome Video",
                    "views": 123123
                },{
                    "id": "asdfasdfasdfasfd",
                    "href": "http://www.youtube.3",
                    "title": "One Awesome Video",
                    "views": 123123
                }]]
            }
        }